/**
 * Body-bound POST client for internal operations on files.teakvault.com.
 * Contracts are shared through @teak/files-protocol; authentication binds the
 * exact JSON bytes, request id, and short expiration into one HMAC.
 */

import {
  buildFilesOpSigningPayload,
  buildMultipartPartSigningPayload,
  buildUploadSigningPayload,
  FILES_OP_PATH,
  FILES_PROTOCOL_VERSION,
  FILES_UPLOAD_MAX_TTL_SECONDS,
  FILES_UPLOAD_PATH,
  type FilesEnvelope,
  type FilesOp,
  type FilesOpRequest,
} from "@teak/files-protocol";
import { hmacSha256Hex } from "./r2";

// Op URLs are minted per action invocation; a short TTL bounds the replay
// window (the worker additionally rejects exps further than 15 min out).
export const FILES_OP_TTL_SECONDS = 10 * 60;

export const isFilesWorkerConfigured = (): boolean =>
  Boolean(process.env.FILES_BASE && process.env.FILES_SIGNING_SECRET);

export interface SignedUploadUrl {
  expiresAt: number;
  key: string;
  url: string;
}

/**
 * Mint a signed single-file PUT URL on the Files Worker. The signature binds
 * the HTTP method, object key, expiry, content type, and — when known ahead
 * of time — the exact byte size. An empty contentType leaves the content type
 * unbound (the worker stores the request's validated Content-Type); use it
 * when the encoding is decided at generation time.
 */
export const buildSignedWorkerUploadUrl = async (
  {
    contentType,
    key,
    size = null,
    ttlSeconds = 10 * 60,
  }: {
    contentType: string;
    key: string;
    size?: number | null;
    ttlSeconds?: number;
  },
  nowSeconds = Math.floor(Date.now() / 1000)
): Promise<SignedUploadUrl> => {
  const base = process.env.FILES_BASE;
  const secret = process.env.FILES_SIGNING_SECRET;
  if (!(base && secret)) {
    throw new Error("files_worker_not_configured");
  }
  if (
    !Number.isSafeInteger(ttlSeconds) ||
    ttlSeconds <= 0 ||
    ttlSeconds > FILES_UPLOAD_MAX_TTL_SECONDS
  ) {
    throw new Error("invalid_upload_ttl");
  }
  const expiresAtNumber = nowSeconds + ttlSeconds;
  const expiresAt = String(expiresAtNumber);
  const signature = await hmacSha256Hex(
    secret,
    buildUploadSigningPayload({ contentType, expiresAt, key, size })
  );
  const url = new URL(
    `${base.replace(/\/+$/, "")}${FILES_UPLOAD_PATH}/${encodeURIComponent(key)}`
  );
  if (contentType) {
    url.searchParams.set("ct", contentType);
  }
  url.searchParams.set("exp", expiresAt);
  url.searchParams.set("sig", signature);
  if (size !== null) {
    url.searchParams.set("sz", String(size));
  }
  return { expiresAt: expiresAtNumber, key, url: url.toString() };
};

/**
 * Upload server-generated bytes through the signed single-file endpoint so
 * they never transit Convex storage. Size is unbound because generated media
 * sizes are only known after generation; the worker enforces its own cap.
 */
export const putObjectViaFilesWorker = async ({
  body,
  contentType,
  key,
}: {
  body: Blob | ArrayBuffer | Uint8Array;
  contentType: string;
  key: string;
}): Promise<{ etag: string; key: string; size: number }> => {
  const signed = await buildSignedWorkerUploadUrl({ contentType, key });
  const response = await fetch(signed.url, {
    body: body instanceof Uint8Array ? new Uint8Array(body) : body,
    headers: {
      "content-type": contentType,
      // Content-Length is set automatically for fixed-size bodies.
      "x-teak-request-id": crypto.randomUUID(),
    },
    method: "PUT",
  });
  const envelope = (await response.json().catch(() => null)) as FilesEnvelope<{
    etag: string;
    key: string;
    size: number;
  }> | null;
  if (!(response.ok && envelope?.ok)) {
    throw new Error(`files_worker_upload_error:${response.status}`);
  }
  return envelope.data;
};

const sha256Hex = async (value: string): Promise<string> => {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(value)
  );
  return Array.from(new Uint8Array(digest), (byte) =>
    byte.toString(16).padStart(2, "0")
  ).join("");
};

export interface SignedWorkerOpRequest {
  body: string;
  headers: Record<string, string>;
  method: "POST";
  url: string;
}

export const buildSignedMultipartPartUrl = async (
  {
    key,
    partNumber,
    uploadId,
  }: { key: string; partNumber: number; uploadId: string },
  nowSeconds = Math.floor(Date.now() / 1000)
): Promise<string> => {
  const base = process.env.FILES_BASE;
  const secret = process.env.FILES_SIGNING_SECRET;
  if (!(base && secret)) {
    throw new Error("files_worker_not_configured");
  }
  const expiresAt = String(nowSeconds + 60 * 60);
  const signature = await hmacSha256Hex(
    secret,
    buildMultipartPartSigningPayload({
      expiresAt,
      key,
      partNumber,
      uploadId,
    })
  );
  const url = new URL(
    `${base.replace(/\/+$/, "")}/__uploads/v1/${encodeURIComponent(uploadId)}/${String(partNumber)}`
  );
  url.searchParams.set("key", key);
  url.searchParams.set("exp", expiresAt);
  url.searchParams.set("sig", signature);
  return url.toString();
};

export const buildSignedWorkerOpRequest = async (
  spec: { op: FilesOp; params: Record<string, unknown> },
  nowSeconds = Math.floor(Date.now() / 1000)
): Promise<SignedWorkerOpRequest> => {
  const base = process.env.FILES_BASE;
  const secret = process.env.FILES_SIGNING_SECRET;
  if (!(base && secret)) {
    throw new Error("files_worker_not_configured");
  }
  const body = JSON.stringify({
    op: spec.op,
    params: spec.params,
    version: FILES_PROTOCOL_VERSION,
  } satisfies FilesOpRequest);
  const bodySha256 = await sha256Hex(body);
  const expiresAt = String(nowSeconds + FILES_OP_TTL_SECONDS);
  const requestId = crypto.randomUUID();
  const signature = await hmacSha256Hex(
    secret,
    buildFilesOpSigningPayload({ bodySha256, expiresAt, requestId })
  );
  return {
    body,
    headers: {
      "content-type": "application/json",
      "x-teak-expires-at": expiresAt,
      "x-teak-request-id": requestId,
      "x-teak-signature": signature,
    },
    method: "POST",
    url: `${base.replace(/\/+$/, "")}${FILES_OP_PATH}`,
  };
};

/**
 * - ok: the op succeeded and returned JSON
 * - fallback: the worker deliberately declined an optional enrichment
 *
 * Network and 5xx responses throw so workflow retries apply.
 */
export type FilesWorkerOutcome<T> =
  | { kind: "ok"; data: T }
  | { kind: "fallback" };

export const callFilesWorkerJson = async <T>(spec: {
  op: FilesOp;
  params: Record<string, unknown>;
}): Promise<FilesWorkerOutcome<T>> => {
  const signed = await buildSignedWorkerOpRequest(spec);
  let response: Response;
  try {
    response = await fetch(signed.url, signed);
  } catch (error) {
    throw new Error(
      `files_worker_network_error:${error instanceof Error ? error.message : String(error)}`
    );
  }
  const envelope = (await response
    .json()
    .catch(() => null)) as FilesEnvelope<T> | null;
  if (!(response.ok && envelope?.ok)) {
    const code = envelope && !envelope.ok ? envelope.error.code : "INTERNAL";
    const requestId =
      envelope && !envelope.ok ? envelope.error.requestId : "unknown";
    if (["NOT_FOUND", "PAYLOAD_TOO_LARGE", "UNSUPPORTED"].includes(code)) {
      return { kind: "fallback" };
    }
    throw new Error(
      `files_worker_error:${code}:${String(response.status)}:${requestId}`
    );
  }
  return { kind: "ok", data: envelope.data };
};

export interface FilesWorkerImageAnalysisResult {
  height: number;
  palette: string[];
  width: number;
}

export interface FilesWorkerBuildExportResult {
  artifactBytes: number;
  filesIncluded: number;
  filesOmitted: number;
  omittedPaths: string[];
}

export interface FilesWorkerInspectResult {
  facts?: Record<string, number>;
  text?: string;
}

export interface FilesWorkerHeadObjectResult {
  contentType?: string;
  etag?: string;
  exists: boolean;
  size?: number;
}

export interface FilesWorkerImageMetadataResult {
  summary: string;
  tags: string[];
}

export interface FilesWorkerListedObject {
  key: string;
  lastModified: number;
  size: number;
}

export interface FilesWorkerListObjectsResult {
  cursor: string | null;
  objects: FilesWorkerListedObject[];
  truncated: boolean;
}
