import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "edge-runtime",
    // A complete WorkOS configuration; tests stub specific values as needed.
    env: {
      CONVEX_SITE_URL: "https://session-tests.convex.site",
      WORKOS_CLIENT_ID: "client_edgetests",
      WORKOS_WEBHOOK_SECRET: "edge-test-webhook-secret",
    },
    include: [
      "./occContention.test.ts",
      "./accountDeletionRetry.test.ts",
      "./accountDeletionStorage.test.ts",
      "./accountDeletionWorkflow.test.ts",
      "./importConsolidation.test.ts",
      "./importUploadDeletion.test.ts",
      "./workosSessions.test.ts",
      "./workosDevices.test.ts",
      "./workosBootstrap.test.ts",
      "./identityTable.test.ts",
      "./workosUsers.test.ts",
      "./workosLifecycle.test.ts",
      "./workosProfileRead.test.ts",
      "./workosIdentity.test.ts",
      "./workosEventCatchUp.test.ts",
      "./workosConsents.test.ts",
      "./workosConnectRevocation.test.ts",
      "./workosApplicationDisconnect.test.ts",
      "./workosBearer.test.ts",
      "./workosDiscovery.test.ts",
      "./workosWebhook.test.ts",
      "./signupFreeze.test.ts",
      "./workosAuthKit.test.ts",
      "./workosDeletionCompletion.test.ts",
      "./publicApiCardEditing.test.ts",
      "./publicApiMe.test.ts",
      "./maintenanceQueries.test.ts",
      "./idempotency.test.ts",
      "./operationalRetention.test.ts",
      "./costOptimization.test.ts",
      "./rawMetadata.test.ts",
      "./rawMetadataPipeline.test.ts",
      "./devSeed.test.ts",
    ],
  },
});
