import { EditorView } from "@codemirror/view";

export const markdownEditorTheme = EditorView.theme({
  "&": {
    backgroundColor: "transparent",
    color: "var(--color-foreground, currentColor)",
    fontFamily: "var(--typeset-font-body, inherit)",
    fontSize: "var(--typeset-size, 1rem)",
    height: "100%",
  },
  "&.cm-focused": { outline: "none" },
  ".cm-scroller": {
    fontFamily: "var(--typeset-font-body, inherit)",
    overflow: "auto",
  },
  ".cm-content": {
    caretColor: "var(--color-foreground, currentColor)",
    lineHeight: "var(--typeset-leading, 1.75)",
    minHeight: "var(--teak-editor-min-height, 5rem)",
    padding: "0",
  },
  ".cm-cursor, .cm-dropCursor": {
    borderLeftColor: "var(--color-foreground, currentColor)",
  },
  ".cm-gutters": { display: "none" },
  ".cm-line": {
    padding: "0",
  },
  ".cm-placeholder": {
    color: "var(--typeset-muted, var(--muted-foreground))",
    fontStyle: "normal",
  },
  "& > .cm-scroller > .cm-selectionLayer .cm-selectionBackground, &.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground":
    {
      backgroundColor: "var(--primary)",
    },
  ".cm-tooltip": {
    backgroundColor: "transparent",
    border: "0",
  },
  ".cm-md-format-toolbar": {
    alignItems: "center",
    backgroundColor: "var(--popover)",
    border: "1px solid var(--border)",
    borderRadius: "0.55rem",
    boxShadow: "0 10px 30px color-mix(in oklch, black 14%, transparent)",
    display: "flex",
    gap: "0.15rem",
    padding: "0.2rem",
  },
  ".cm-md-format-button": {
    alignItems: "center",
    background: "transparent",
    border: "0",
    borderRadius: "0.35rem",
    color: "var(--popover-foreground)",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "var(--font-sans, sans-serif)",
    fontSize: "0.72rem",
    fontWeight: "650",
    height: "1.75rem",
    justifyContent: "center",
    minWidth: "1.75rem",
    padding: "0 0.35rem",
  },
  ".cm-md-format-button:hover, .cm-md-format-button:focus-visible": {
    backgroundColor: "var(--accent)",
    color: "var(--accent-foreground)",
    outline: "none",
  },
  ".cm-md-heading": {
    color: "var(--color-foreground, currentColor)",
    fontFamily: "var(--typeset-font-heading, inherit)",
    fontWeight: "600",
  },
  ".cm-md-heading-1": { fontSize: "1.75em", lineHeight: "1.3" },
  ".cm-md-heading-2": { fontSize: "1.25em", lineHeight: "1.4" },
  ".cm-md-heading-3": { fontSize: "1.125em", lineHeight: "1.45" },
  ".cm-md-heading-4": { fontSize: "1em", lineHeight: "1.5" },
  ".cm-md-heading-5": {
    color: "var(--typeset-muted)",
    fontSize: "0.875em",
  },
  ".cm-md-heading-6": {
    color: "var(--typeset-muted)",
    fontSize: "0.8125em",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  ".cm-md-strong": { fontWeight: "600" },
  ".cm-md-emphasis": { fontStyle: "italic" },
  ".cm-md-strikethrough, .cm-md-task-complete": {
    color: "var(--typeset-muted, var(--muted-foreground))",
    textDecoration: "line-through",
  },
  ".cm-md-inline-code": {
    backgroundColor: "var(--muted)",
    borderRadius: "0.25rem",
    fontFamily: "var(--typeset-font-mono, monospace)",
    fontSize: "0.86em",
    padding: "0.04rem 0.2rem",
  },
  ".cm-md-code-line": {
    backgroundColor: "color-mix(in oklch, var(--muted) 72%, transparent)",
    borderLeft: "1px solid var(--border)",
    borderRight: "1px solid var(--border)",
    boxSizing: "border-box",
    fontFamily: "var(--typeset-font-mono, monospace)",
    fontSize: "0.86em",
    lineHeight: "1.55",
    paddingLeft: "0.8rem",
    paddingRight: "0.8rem",
    tabSize: "2",
  },
  ".cm-md-code-first": {
    borderRadius: "0.5rem 0.5rem 0 0",
    borderTop: "1px solid var(--border)",
    color: "var(--typeset-muted, var(--muted-foreground))",
    fontSize: "0.72em",
    letterSpacing: "0.06em",
    marginTop: "var(--typeset-flow, 1.25em)",
    paddingBottom: "0.25rem",
    paddingTop: "0.45rem",
    textTransform: "uppercase",
  },
  ".cm-md-code-last": {
    borderBottom: "1px solid var(--border)",
    borderRadius: "0 0 0.5rem 0.5rem",
    paddingBottom: "0.45rem",
  },
  ".cm-md-code-first.cm-md-code-last": {
    borderRadius: "0.5rem",
  },
  ".cm-md-code-fence-hidden": {
    fontSize: "0",
    height: "0",
    lineHeight: "0",
    overflow: "hidden",
    padding: "0",
  },
  ".cm-md-comment": {
    color: "var(--typeset-muted, var(--muted-foreground))",
    fontFamily: "var(--typeset-font-mono, monospace)",
    fontSize: "0.82em",
    opacity: "0.62",
  },
  ".cm-md-table-shell": {
    backgroundColor: "color-mix(in oklch, var(--muted) 42%, transparent)",
    border: "1px solid var(--border)",
    borderRadius: "0.5rem",
    cursor: "text",
    marginTop: "var(--typeset-flow, 1.25em)",
    overflowX: "auto",
  },
  ".cm-md-table": {
    borderCollapse: "separate",
    borderSpacing: "0",
    fontSize: "0.9em",
    lineHeight: "1.45",
    width: "100%",
  },
  ".cm-md-table th, .cm-md-table td": {
    borderBottom: "1px solid var(--border)",
    padding: "0.5rem 0.65rem",
    verticalAlign: "top",
  },
  ".cm-md-table th + th, .cm-md-table td + td": {
    borderLeft: "1px solid var(--border)",
  },
  ".cm-md-table th": {
    backgroundColor: "color-mix(in oklch, var(--muted) 68%, transparent)",
    fontWeight: "600",
  },
  ".cm-md-table tbody tr:last-child td": {
    borderBottom: "0",
  },
  ".cm-md-table code": {
    backgroundColor: "var(--muted)",
    borderRadius: "0.25rem",
    fontFamily: "var(--typeset-font-mono, monospace)",
    fontSize: "0.88em",
    padding: "0.08rem 0.25rem",
  },
  ".cm-md-quote": {
    borderLeft: "2px solid var(--typeset-rule, var(--border))",
    color: "var(--typeset-muted, var(--muted-foreground))",
    paddingLeft: "0.65rem",
  },
  ".cm-md-divider": {
    borderTop: "1px solid var(--typeset-rule, var(--border))",
    height: "var(--typeset-flow, 1.25em)",
    marginTop: "var(--typeset-flow, 1.25em)",
  },
  ".cm-md-syntax, .cm-md-image-source": {
    color: "var(--typeset-muted, var(--muted-foreground))",
    fontSize: "0.88em",
  },
  ".cm-md-list-marker": {
    color: "var(--typeset-muted, var(--muted-foreground))",
    display: "inline-block",
    minWidth: "1.35rem",
    paddingLeft: "0.15rem",
  },
  ".cm-md-task-checkbox": {
    accentColor: "var(--primary)",
    cursor: "pointer",
    height: "0.95rem",
    margin: "0 0.45rem 0 0.1rem",
    verticalAlign: "-0.12rem",
    width: "0.95rem",
  },
  ".cm-md-task-checkbox:disabled": {
    cursor: "default",
    opacity: "0.62",
  },
  ".cm-md-link-shell": {
    display: "inline",
    position: "relative",
  },
  ".cm-md-link": {
    background: "transparent",
    border: "0",
    color: "inherit",
    cursor: "pointer",
    font: "inherit",
    fontWeight: "500",
    padding: "0",
    textDecoration: "underline",
    textDecorationColor: "color-mix(in oklab, currentColor 30%, transparent)",
    textUnderlineOffset: "0.15em",
  },
  ".cm-md-link-unsafe": {
    color: "var(--muted-foreground)",
    textDecorationStyle: "dotted",
  },
  ".cm-md-link-popover": {
    alignItems: "center",
    backgroundColor: "var(--popover)",
    border: "1px solid var(--border)",
    borderRadius: "0.5rem",
    boxShadow: "0 10px 30px color-mix(in oklch, black 14%, transparent)",
    display: "inline-flex",
    gap: "0.15rem",
    left: "0",
    padding: "0.2rem",
    position: "absolute",
    top: "calc(100% + 0.35rem)",
    whiteSpace: "nowrap",
    zIndex: "20",
  },
  ".cm-md-link-popover[hidden]": {
    display: "none",
  },
  ".cm-md-link-popover button": {
    background: "transparent",
    border: "0",
    borderRadius: "0.35rem",
    color: "var(--popover-foreground)",
    cursor: "pointer",
    fontFamily: "var(--font-sans, sans-serif)",
    fontSize: "0.72rem",
    fontWeight: "600",
    height: "1.75rem",
    padding: "0 0.5rem",
  },
  ".cm-md-link-popover button:hover, .cm-md-link-popover button:focus-visible":
    {
      backgroundColor: "var(--accent)",
      color: "var(--accent-foreground)",
      outline: "none",
    },
});
