/**
 * Environment contract entries: cli, worker bindings, e2e, release, and repo tooling.
 *
 * One third of ENV_CONTRACT, assembled in ./env-contract.ts. Names and
 * metadata only - never values.
 */

import { type EnvVarSpec, spec } from "./env-contract-types.ts";

export const OPS_ENTRIES: EnvVarSpec[] = [
  // CLI runtime.
  spec("TEAK_AUTH_URL", {
    owners: ["teak-cli"],
    targets: ["cli"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_API_URL", {
    owners: ["teak-cli", "@teak/tests"],
    targets: ["cli", "e2e"],
    profiles: ["local", "preview", "production", "e2e"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
    note: "The prod E2E CLI harness injects this per run; it is not a suite origin.",
  }),
  spec("TEAK_API_KEY", {
    owners: ["teak-cli", "@teak/tests"],
    targets: ["cli", "e2e"],
    profiles: ["local", "preview", "production", "e2e"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_API_REQUEST_TIMEOUT_MS", {
    owners: ["teak-cli", "teak-raycast"],
    targets: ["cli", "raycast"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "number",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  // Files Worker bindings (Cloudflare bindings, not plain env).
  spec("BUCKET", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    kind: "binding",
    note: "R2 bucket binding backing file storage.",
  }),
  spec("OBJECT_GATES", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    kind: "binding",
    note: "Durable exact-key write fencing for safe account deletion.",
  }),
  spec("AI", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: false,
    kind: "binding",
    note: "Workers AI binding for image analysis and transcripts.",
  }),
  spec("IMAGES", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: false,
    kind: "binding",
    note: "Cloudflare Images binding for transforms.",
  }),
  // E2E suite.
  spec("TEAK_E2E_RUN_STATE_FILE", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "path",
    providers: ["workflow", "dotenv-local", "shell"],
    required: false,
  }),
  // Release secrets (GitHub-hosted, never local defaults).
  spec("TEAK_SDK_RELEASE_ARTIFACT", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["local", "production"],
    secret: false,
    validation: "path",
    providers: ["workflow", "shell"],
    required: false,
    note: "Exact packed SDK tarball exercised by the independent consumer before publication.",
  }),
  spec("APPLE_CERTIFICATE_PASSWORD", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("APPLE_DISTRIBUTION_PRIVATE_KEY_BASE64", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_CLIENT_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_CLIENT_SECRET", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_EXTENSION_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_PUBLISHER_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_REFRESH_TOKEN", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("SENTRY_MOBILE_DSN", {
    owners: ["teak-release"],
    targets: ["release", "mobile"],
    profiles: ["production"],
    secret: true,
    validation: "url",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
    note: "CI secret mapped to EXPO_PUBLIC_SENTRY_MOBILE_DSN at release time.",
  }),
  spec("MAC_SCREENSHOT_BROWSER", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local"],
    secret: false,
    validation: "path",
    providers: ["shell"],
    required: false,
    note: "Optional browser executable override for the Mac screenshot renderer.",
  }),
  // Repo tooling and smoke scripts.
  spec("SMOKE_WORKOS_CREDENTIALS", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local"],
    secret: false,
    validation: "enum",
    allowedValues: ["present", "fork", "missing"],
    providers: ["workflow", "shell"],
    required: false,
    note: "Clean-container smoke: whether the web's WorkOS credentials are real. Unset means present.",
  }),
  ...["WORKOS_STAGING_CLIENT_ID", "WORKOS_STAGING_API_KEY"].map((name) =>
    spec(name, {
      owners: ["teak-repo"],
      targets: ["repo"],
      profiles: ["local"],
      secret: name === "WORKOS_STAGING_API_KEY",
      validation: "string",
      providers: ["github-secrets"],
      required: false,
      note: "WorkOS staging environment (the one the dev deployment uses), mapped to WORKOS_CLIENT_ID/WORKOS_API_KEY by the clean-container smoke. Never production.",
    })
  ),
  spec("CONVEX_AGENT_MODE", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local", "e2e"],
    secret: false,
    validation: "enum",
    allowedValues: ["anonymous"],
    providers: ["shell", "workflow"],
    required: false,
    note: "Explicit Convex CLI mode for isolated anonymous local development and smoke checks.",
  }),
  spec("TURBO_TOKEN", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local", "vercel"],
    required: false,
    implicit: true,
    note: "Consumed implicitly by the Turbo CLI for Remote Cache auth.",
  }),
  spec("TURBO_TEAM", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["dotenv-local", "vercel"],
    required: false,
    implicit: true,
    note: "Consumed implicitly by the Turbo CLI for Remote Cache scope.",
  }),
  spec("BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["workflow", "shell"],
    required: false,
    note: "Smoke-script target. Defaults to the production origin.",
  }),
  spec("SMOKE_BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["shell"],
    required: false,
    note: "Shell override for the smoke-script target.",
  }),
  spec("EXPECTED_BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["shell"],
    required: false,
    note: "Shell override for the expected canonical origin in smoke assertions.",
  }),
];
