/**
 * Environment contract entries: dev-url overrides and web, desktop, extension, and mobile clients.
 *
 * One third of ENV_CONTRACT, assembled in ./env-contract.ts. Names and
 * metadata only - never values.
 */

import { type EnvVarSpec, spec } from "./env-contract-types.ts";

export const SURFACE_ENTRIES: EnvVarSpec[] = [
  // Local dev-URL overrides (shared resolver in @teak/convex/dev-urls).
  spec("TEAK_DEV_APP_URL", {
    owners: [
      "@teak/convex",
      "@teak/web",
      "@teak/extension",
      "@teak/desktop",
      "@teak/docs",
    ],
    targets: ["convex", "web", "extension", "desktop", "docs"],
    profiles: ["local"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_DEV_API_URL", {
    owners: ["@teak/convex", "teak-raycast", "@teak/docs"],
    targets: ["convex", "raycast", "docs"],
    profiles: ["local"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_DEV_DOCS_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_DEV_CONVEX_SITE_URL", {
    owners: ["teak-raycast"],
    targets: ["raycast"],
    profiles: ["local"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  // Web client.
  spec("NEXT_PUBLIC_CONVEX_URL", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "vercel"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("NEXT_PUBLIC_CONVEX_SITE_URL", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "vercel"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("NEXT_PUBLIC_SENTRY_ENVIRONMENT", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "preview", "development", "test"],
    providers: ["vercel"],
    required: false,
  }),
  spec("NEXT_PUBLIC_SENTRY_DSN", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["vercel"],
    required: false,
    note: "Client-exposed by design; the secret flag stays off for DSNs shipped in bundles.",
  }),
  spec("NEXT_PUBLIC_SENTRY_RELEASE", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["build", "vercel"],
    required: false,
    note: "Written by next.config from the app version and commit SHA.",
  }),
  spec("NEXT_PUBLIC_APP_VERSION", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["build"],
    required: false,
    note: "Written by next.config from package.json for release derivation.",
  }),
  spec("NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA", {
    owners: ["@teak/web"],
    targets: ["web"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "sha",
    providers: ["build"],
    required: false,
    note: "Written by next.config from provider commit metadata.",
  }),
  spec("GIT_SHA", {
    owners: ["@teak/web", "@teak/desktop"],
    targets: ["web", "desktop"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "sha",
    providers: ["workflow", "shell"],
    required: false,
    note: "Manual commit-SHA override for release derivation outside Vercel/GitHub.",
  }),
  // Desktop and extension (Vite).
  spec("VITE_PUBLIC_CONVEX_URL", {
    owners: ["@teak/desktop", "@teak/extension"],
    targets: ["desktop", "extension"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "workflow"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("VITE_PUBLIC_CONVEX_SITE_URL", {
    owners: ["@teak/desktop", "@teak/extension"],
    targets: ["desktop", "extension"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "workflow"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("VITE_WEB_URL", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "workflow"],
    required: false,
  }),
  spec("VITE_SENTRY_ENVIRONMENT", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "preview", "development", "test"],
    providers: ["workflow"],
    required: false,
  }),
  spec("VITE_SENTRY_RELEASE", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["workflow", "build"],
    required: false,
  }),
  spec("VITE_PUBLIC_SENTRY_DESKTOP_DSN", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["production"],
    secret: false,
    validation: "url",
    providers: ["github-secrets", "workflow"],
    required: true,
    requiredIn: ["production"],
    note: "Client-exposed by design; asserted by verify-sentry-release-env for releases.",
  }),
  spec("VITE_GIT_COMMIT_SHA", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["production"],
    secret: false,
    validation: "sha",
    providers: ["workflow"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("VITE_DESKTOP_UPDATE_CHANNEL", {
    owners: ["@teak/desktop"],
    targets: ["desktop"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["stable", "beta"],
    providers: ["workflow"],
    required: false,
  }),
  // Mobile (Expo / EAS).
  spec("EXPO_PUBLIC_CONVEX_URL", {
    owners: ["@teak/mobile"],
    targets: ["mobile"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "eas"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("EXPO_PUBLIC_CONVEX_SITE_URL", {
    owners: ["@teak/mobile"],
    targets: ["mobile"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "eas"],
    required: true,
    requiredIn: ["local", "preview", "production"],
  }),
  spec("EXPO_PUBLIC_SENTRY_ENVIRONMENT", {
    owners: ["@teak/mobile"],
    targets: ["mobile"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "preview", "development", "test"],
    providers: ["eas"],
    required: false,
  }),
  spec("EXPO_PUBLIC_SENTRY_MOBILE_DSN", {
    owners: ["@teak/mobile"],
    targets: ["mobile"],
    profiles: ["production"],
    secret: false,
    validation: "url",
    providers: ["github-secrets", "eas"],
    required: true,
    requiredIn: ["production"],
    note: "Client-exposed by design; asserted for production EAS builds.",
  }),
  spec("TEAK_IOS_BUILD_NUMBER", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow", "dotenv-local"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("TEAK_IOS_VERSION", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow", "dotenv-local"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("APPLE_DISTRIBUTION_IDENTITY", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("IOS_APP_PROFILE_NAME", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("IOS_EXTENSION_PROFILE_NAME", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("APPLE_API_ISSUER", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets", "dotenv-local"],
    required: false,
    note: "Local release signing and CI. Never a local-dev default.",
  }),
  spec("APPLE_API_KEY_ID", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets", "dotenv-local"],
    required: false,
  }),
  spec("APPLE_API_KEY_PATH", {
    owners: ["@teak/mobile"],
    targets: ["mobile", "release"],
    profiles: ["production"],
    secret: false,
    validation: "path",
    providers: ["github-secrets", "workflow", "dotenv-local"],
    required: false,
  }),
  spec("APPLE_API_KEY_P8", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
];
