/**
 * Environment contract entries: convex backend, capability groups, and deployment plumbing.
 *
 * One third of ENV_CONTRACT, assembled in ./env-contract.ts. Names and
 * metadata only - never values.
 */

import { type EnvVarSpec, spec } from "./env-contract-types.ts";

export const BACKEND_ENTRIES: EnvVarSpec[] = [
  spec("SIGNUPS_DISABLED", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["true", "false"],
    providers: ["convex-dashboard"],
    required: false,
    note: "Migration sign-up freeze. Unset means sign-ups remain open.",
  }),
  spec("ACCOUNT_CHANGES_PAUSED", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["true", "false"],
    providers: ["convex-dashboard"],
    required: false,
    note: "Migration account-change pause. Unset means account changes remain available.",
  }),
  // WorkOS AuthKit is the only sign-in provider; every deployment needs it.
  spec("WORKOS_CLIENT_ID", {
    owners: ["@teak/convex", "@teak/web"],
    targets: ["convex", "web"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard", "dotenv-local", "vercel"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    implicit: true,
    note: "Convex-managed source, synced by setup to the web server dotenv (Vercel by hand) for the same deployment. Local and CI use a WorkOS staging environment; production stays separate.",
  }),
  spec("WORKOS_API_KEY", {
    owners: ["@teak/convex", "@teak/web"],
    targets: ["convex", "web"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "dotenv-local", "vercel"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    implicit: true,
    note: "Convex-managed source, synced by setup to the web server dotenv (Vercel by hand) for the same deployment. Never expose in a client bundle or copy production credentials locally.",
  }),
  spec("WORKOS_AUTHKIT_DOMAIN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
    note: "HTTPS origin of this deployment's WorkOS Connect issuer. No trailing slash or path.",
  }),
  ...[
    "WORKOS_CONNECT_CLI_CLIENT_ID",
    "WORKOS_CONNECT_RAYCAST_CLIENT_ID",
    "WORKOS_CONNECT_CHROME_CLIENT_ID",
    "WORKOS_CONNECT_FIREFOX_CLIENT_ID",
    "WORKOS_CONNECT_SAFARI_CLIENT_ID",
  ].map((name) =>
    spec(name, {
      owners: ["@teak/convex"],
      targets: ["convex"],
      profiles: ["local", "preview", "production"],
      secret: false,
      validation: "string",
      providers: ["convex-dashboard"],
      required: false,
      note: "Deployment-specific first-party WorkOS Connect public app for that surface's sign-in.",
    })
  ),
  ...["WORKOS_RECONCILIATION_MODE", "WORKOS_RECONCILIATION_WITNESS_ID"].map(
    (name) =>
      spec(name, {
        owners: ["@teak/convex"],
        targets: ["convex"],
        profiles: ["local", "preview", "production"],
        secret: false,
        validation: "string",
        providers: ["convex-dashboard"],
        required: false,
        note: "Daily reconciliation audit controls. Mode unset/off is inert; audit and pinned provider witness require separate operator activation. No scheduled repair.",
      })
  ),
  spec("WORKOS_API_BASE_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "e2e"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard", "shell"],
    required: false,
    note: "Unset in hosted deployments. A local stack sets the WorkOS emulator's loopback origin.",
  }),
  spec("WORKOS_ENVIRONMENT_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "WorkOS environment associated with this Convex deployment.",
  }),
  spec("WORKOS_WEBHOOK_SECRET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "WorkOS callback signing secret. Separate per environment.",
  }),
  spec("WORKOS_ACTION_SECRET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "WorkOS callback signing secret. Separate per environment.",
  }),
  // Convex backend core.
  spec("SITE_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    note: "Canonical web app origin for links and trusted origins. Configured by setup locally.",
  }),
  spec("PUBLIC_ORIGIN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "origin",
    providers: ["convex-dashboard"],
    required: false,
    note: "Public origin for self-hosted /api and /mcp. Optional locally; required when self-hosting public endpoints.",
  }),
  // Canonical deployment facts. Framework aliases derive from these via
  // scripts/env-aliases.ts; nothing reads the canonical names directly.
  spec("CONVEX_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
    implicit: true,
    note: "Canonical deployment API URL. Local values come from convex dev; setup expands it into NEXT/VITE/EXPO_PUBLIC_CONVEX_URL.",
  }),
  spec("CONVEX_SITE_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
    implicit: true,
    note: "Canonical deployment HTTP-actions URL. Setup expands it into the NEXT/VITE/EXPO_PUBLIC_CONVEX_SITE_URL aliases.",
  }),
  // Files / R2 capability group.
  ...["FILES_TEXT_AI_ENABLED", "OPERATIONAL_RETENTION_ENABLED"].map((name) =>
    spec(name, {
      owners: ["@teak/convex"],
      targets: ["convex"],
      profiles: ["local", "preview", "production"],
      secret: false,
      validation: "boolean",
      providers: ["convex-dashboard"],
      required: false,
      note: "Optional staged rollout switch. Only true enables the capability; unset stays disabled.",
    })
  ),
  spec("FILES_BASE", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
  }),

  spec("FILES_SIGNING_SECRET", {
    owners: ["@teak/convex", "@teak/files-worker"],
    targets: ["convex", "files-worker"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "wrangler-secret", "dotenv-local"],
    required: false,
    note: "HMAC secret shared by Convex and its Files Worker. Shared dev routing reuses the production value; isolated dev routing requires its own. Convex dev syncs to files-worker .dev.vars (or development/.dev.vars with --isolated).",
  }),
  spec("R2_BUCKET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_ENDPOINT", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_ACCESS_KEY_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_SECRET_ACCESS_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_KEY_PREFIX", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Cloudflare AI capability group.
  spec("CLOUDFLARE_ACCOUNT_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("CLOUDFLARE_API_TOKEN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Media / email SDK and component credentials (implicit reads).
  spec("KERNEL_API_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "sdk-implicit"],
    required: false,
    implicit: true,
    note: "Read implicitly by @onkernel/sdk default auth (screenshots, thumbnails, link metadata).",
  }),
  spec("RESEND_API_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "component-implicit"],
    required: false,
    implicit: true,
    note: "Read implicitly by the @convex-dev/resend component.",
  }),
  // Polar billing capability group.
  spec("POLAR_ACCESS_TOKEN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("POLAR_SERVER", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "sandbox"],
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Sentry capability group (shared across surfaces).
  spec("SENTRY_ENVIRONMENT", {
    owners: ["@teak/convex", "@teak/web", "@teak/files-worker"],
    targets: ["convex", "web", "files-worker"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "preview", "development", "test"],
    providers: ["convex-dashboard", "vercel", "wrangler-var"],
    required: false,
    note: "Explicit label. Convex keeps it (no deployment classification there); other surfaces prefer provider metadata.",
  }),
  spec("SENTRY_RELEASE", {
    owners: [
      "@teak/convex",
      "@teak/web",
      "@teak/desktop",
      "@teak/files-worker",
    ],
    targets: ["convex", "web", "desktop", "files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["workflow", "build", "vercel", "wrangler-var"],
    required: false,
    note: "Explicit override. Releases otherwise derive from app version plus commit SHA.",
  }),
  spec("SENTRY_BACKEND_DSN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "url",
    providers: ["convex-dashboard", "github-secrets"],
    required: false,
    note: "Single writer is the GitHub secret; Backend Deploy stamps it into the Convex dashboard each release.",
  }),
  spec("SENTRY_DSN", {
    owners: ["@teak/convex", "@teak/web", "@teak/files-worker"],
    targets: ["convex", "web", "files-worker"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "url",
    providers: ["convex-dashboard", "vercel", "wrangler-secret"],
    required: false,
    note: "Convex and web fallback when the surface-specific DSN is unset; the worker's only DSN.",
  }),
  spec("SENTRY_AUTH_TOKEN", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
    note: "Release-only sourcemap upload credential. Never a local default.",
  }),
  spec("SENTRY_ORG", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: false,
    implicit: true,
    note: "Consumed by sentry-cli during releases.",
  }),
  spec("SENTRY_PROJECT", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: false,
    implicit: true,
    note: "Consumed by sentry-cli during releases.",
  }),
  // E2E backend capability group.
  spec("E2E_CLEANUP_TOKEN", {
    owners: ["@teak/convex", "@teak/tests"],
    targets: ["convex", "e2e"],
    profiles: ["e2e"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
    note: "Single writer is the operator: the same Bearer [REDACTED] is stored in the Convex dashboard and the GitHub secret, and must match.",
  }),
  spec("E2E_EMAIL_DOMAIN", {
    owners: ["@teak/convex", "@teak/tests"],
    targets: ["convex", "e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard", "github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
    note: "Single writer is the operator: the private MX domain is mirrored in the Convex dashboard and CI, and must match.",
  }),
  // Convex deployment plumbing.
  spec("CONVEX_DEPLOY_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex", "release"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets", "dotenv-local"],
    required: false,
    note: "Selects a deployment for non-interactive Convex CLI runs. Setup refuses it locally.",
  }),
  spec("CONVEX_GIT_COMMIT_SHA", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "sha",
    providers: ["workflow"],
    required: false,
    derivedFrom: "provider commit metadata via scripts/build-metadata.ts",
    note: "Stamped by Backend Deploy for the backend Sentry release.",
  }),
];
