/**
 * Environment contract entries: cli, worker bindings, e2e, release, and repo tooling.
 *
 * One third of ENV_CONTRACT, assembled in ./env-contract.ts. Names and
 * metadata only - never values.
 */

import { type EnvVarSpec, spec } from "./env-contract-types.ts";

export const OPS_ENTRIES: EnvVarSpec[] = [
  // CLI runtime.
  spec("TEAK_AUTH_URL", {
    owners: ["teak-cli"],
    targets: ["cli"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_API_URL", {
    owners: ["teak-cli", "@teak/tests"],
    targets: ["cli", "e2e"],
    profiles: ["local", "preview", "production", "e2e"],
    secret: false,
    validation: "url",
    providers: ["dotenv-local", "shell"],
    required: false,
    note: "The prod E2E CLI harness injects this per run; it is not a suite origin.",
  }),
  spec("TEAK_API_KEY", {
    owners: ["teak-cli", "@teak/tests"],
    targets: ["cli", "e2e"],
    profiles: ["local", "preview", "production", "e2e"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_API_REQUEST_TIMEOUT_MS", {
    owners: ["teak-cli", "teak-raycast"],
    targets: ["cli", "raycast"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "number",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  // Files Worker bindings (Cloudflare bindings, not plain env).
  spec("BUCKET", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    kind: "binding",
    note: "R2 bucket binding backing file storage.",
  }),
  spec("AI", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: false,
    kind: "binding",
    note: "Workers AI binding for image analysis and transcripts.",
  }),
  spec("IMAGES", {
    owners: ["@teak/files-worker"],
    targets: ["files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["cloudflare"],
    required: false,
    kind: "binding",
    note: "Cloudflare Images binding for transforms.",
  }),
  // E2E suite origins (one family, no cross-framework fallbacks).
  spec("E2E_PUBLIC_ORIGIN", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "origin",
    providers: ["github-secrets", "dotenv-local", "workflow"],
    required: true,
    requiredIn: ["e2e"],
    note: "Canonical E2E origin. /api and /mcp paths derive from it.",
  }),
  spec("E2E_APP_ORIGIN", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "origin",
    providers: ["github-secrets", "dotenv-local", "workflow"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("E2E_CONVEX_URL", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "url",
    providers: ["github-secrets", "dotenv-local", "workflow"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("E2E_CONVEX_SITE_URL", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "url",
    providers: ["github-secrets", "dotenv-local", "workflow"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("PROD_E2E_PASSWORD", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: true,
    validation: "string",
    providers: ["github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("MAILPIT_URL", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "url",
    providers: ["github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("E2E_EMAIL_DELIVERY_ENABLED", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "boolean",
    providers: ["workflow", "dotenv-local"],
    required: false,
  }),
  spec("PROD_E2E_API_BUDGET_MS", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "number",
    providers: ["workflow", "dotenv-local"],
    required: false,
  }),
  spec("PROD_E2E_DOCS_PAGE_LIMIT", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "number",
    providers: ["workflow", "dotenv-local"],
    required: false,
  }),
  spec("TEAK_NPM_BIN", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "path",
    providers: ["workflow", "dotenv-local", "shell"],
    required: false,
  }),
  spec("TEAK_E2E_RUN_STATE_FILE", {
    owners: ["@teak/tests"],
    targets: ["e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "path",
    providers: ["workflow", "dotenv-local", "shell"],
    required: false,
  }),
  // Local web E2E credentials.
  spec("E2E_BETTER_AUTH_USER_EMAIL", {
    owners: ["@teak/web"],
    targets: ["web", "e2e"],
    profiles: ["local", "e2e"],
    secret: false,
    validation: "email",
    providers: ["dotenv-local"],
    required: false,
  }),
  spec("E2E_BETTER_AUTH_USER_PASSWORD", {
    owners: ["@teak/web"],
    targets: ["web", "e2e"],
    profiles: ["local", "e2e"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local"],
    required: false,
  }),
  spec("E2E_TEST_EMAIL", {
    owners: ["@teak/web"],
    targets: ["web", "e2e"],
    profiles: ["local", "e2e"],
    secret: false,
    validation: "email",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("E2E_TEST_PASSWORD", {
    owners: ["@teak/web"],
    targets: ["web", "e2e"],
    profiles: ["local", "e2e"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  spec("SKIP_AUTH_TESTS", {
    owners: ["@teak/web"],
    targets: ["web", "e2e"],
    profiles: ["local", "e2e"],
    secret: false,
    validation: "boolean",
    providers: ["dotenv-local", "shell"],
    required: false,
  }),
  // Release secrets (GitHub-hosted, never local defaults).
  spec("APPLE_CERTIFICATE_PASSWORD", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("APPLE_DISTRIBUTION_PRIVATE_KEY_BASE64", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_CLIENT_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_CLIENT_SECRET", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_EXTENSION_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_PUBLISHER_ID", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CHROME_REFRESH_TOKEN", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CSC_LINK", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("CSC_KEY_PASSWORD", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
  }),
  spec("SENTRY_DESKTOP_DSN", {
    owners: ["teak-release"],
    targets: ["release", "desktop"],
    profiles: ["production"],
    secret: true,
    validation: "url",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
    note: "CI secret mapped to VITE_PUBLIC_SENTRY_DESKTOP_DSN at release time.",
  }),
  spec("SENTRY_MOBILE_DSN", {
    owners: ["teak-release"],
    targets: ["release", "mobile"],
    profiles: ["production"],
    secret: true,
    validation: "url",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
    note: "CI secret mapped to EXPO_PUBLIC_SENTRY_MOBILE_DSN at release time.",
  }),
  // Repo tooling and smoke scripts.
  spec("TURBO_TOKEN", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["dotenv-local", "vercel"],
    required: false,
    implicit: true,
    note: "Consumed implicitly by the Turbo CLI for Remote Cache auth.",
  }),
  spec("TURBO_TEAM", {
    owners: ["teak-repo"],
    targets: ["repo"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["dotenv-local", "vercel"],
    required: false,
    implicit: true,
    note: "Consumed implicitly by the Turbo CLI for Remote Cache scope.",
  }),
  spec("BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["workflow", "shell"],
    required: false,
    note: "Smoke-script target. Defaults to the production origin.",
  }),
  spec("SMOKE_BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["shell"],
    required: false,
    note: "Shell override for the smoke-script target.",
  }),
  spec("EXPECTED_BASE_URL", {
    owners: ["teak-repo"],
    targets: ["repo", "e2e"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "url",
    providers: ["shell"],
    required: false,
    note: "Shell override for the expected canonical origin in smoke assertions.",
  }),
];
