/**
 * Environment contract entries: convex backend, capability groups, and deployment plumbing.
 *
 * One third of ENV_CONTRACT, assembled in ./env-contract.ts. Names and
 * metadata only - never values.
 */

import { type EnvVarSpec, spec } from "./env-contract-types.ts";

export const BACKEND_ENTRIES: EnvVarSpec[] = [
  // Convex backend core.
  spec("SITE_URL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: true,
    requiredIn: ["local", "preview", "production"],
    note: "Better Auth baseURL and OAuth issuer origin. Configured by setup locally.",
  }),
  spec("PUBLIC_ORIGIN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "origin",
    providers: ["convex-dashboard"],
    required: false,
    note: "Optional public origin. /api and /mcp endpoints derive from it.",
  }),
  spec("JWKS", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "Public JWKS for the Convex auth bridge.",
  }),
  spec("BETTER_AUTH_SECRET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "component-implicit"],
    required: false,
    implicit: true,
    note: "Read implicitly by the @convex-dev/better-auth component.",
  }),
  // Google capability group (atomic pair, optional as a whole).
  spec("GOOGLE_CLIENT_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "Google auth group. Absent locally; a lone ID without its secret is invalid.",
  }),
  spec("GOOGLE_CLIENT_SECRET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
    note: "Google auth group. Absent locally; a lone secret without its ID is invalid.",
  }),
  // Apple capability group (atomic set, optional as a whole).
  spec("APPLE_CLIENT_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("APPLE_KEY_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("APPLE_PRIVATE_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("APPLE_TEAM_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("APPLE_APP_BUNDLE_IDENTIFIER", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Files / R2 capability group.
  spec("FILES_BASE", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("FILES_LEGACY_BASE", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
    note: "Preserved storage-compatibility base. No migration in this change.",
  }),
  spec("FILES_SIGNING_SECRET", {
    owners: ["@teak/convex", "@teak/files-worker"],
    targets: ["convex", "files-worker"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "wrangler-secret", "dotenv-local"],
    required: false,
    note: "Shared HMAC secret. Convex dashboard value syncs to files-worker .dev.vars locally.",
  }),
  spec("R2_BUCKET", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_ENDPOINT", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "url",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_ACCESS_KEY_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_SECRET_ACCESS_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("R2_KEY_PREFIX", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Cloudflare AI capability group.
  spec("CLOUDFLARE_ACCOUNT_ID", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("CLOUDFLARE_API_TOKEN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Media / email SDK and component credentials (implicit reads).
  spec("KERNEL_API_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "sdk-implicit"],
    required: false,
    implicit: true,
    note: "Read implicitly by @onkernel/sdk default auth (screenshots, thumbnails, link metadata).",
  }),
  spec("RESEND_API_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "component-implicit"],
    required: false,
    implicit: true,
    note: "Read implicitly by the @convex-dev/resend component.",
  }),
  // Polar billing capability group.
  spec("POLAR_ACCESS_TOKEN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard"],
    required: false,
  }),
  spec("POLAR_SERVER", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "sandbox"],
    providers: ["convex-dashboard"],
    required: false,
  }),
  // Sentry capability group (shared across surfaces).
  spec("SENTRY_ENVIRONMENT", {
    owners: ["@teak/convex", "@teak/web", "@teak/files-worker"],
    targets: ["convex", "web", "files-worker"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "enum",
    allowedValues: ["production", "preview", "development", "test"],
    providers: ["convex-dashboard", "vercel", "wrangler-var"],
    required: false,
    note: "Explicit label. Convex keeps it (no deployment classification there); other surfaces prefer provider metadata.",
  }),
  spec("SENTRY_RELEASE", {
    owners: [
      "@teak/convex",
      "@teak/web",
      "@teak/desktop",
      "@teak/files-worker",
    ],
    targets: ["convex", "web", "desktop", "files-worker"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "string",
    providers: ["workflow", "build", "vercel", "wrangler-var"],
    required: false,
    note: "Explicit override. Releases otherwise derive from app version plus commit SHA.",
  }),
  spec("SENTRY_BACKEND_DSN", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "url",
    providers: ["convex-dashboard", "github-secrets"],
    required: false,
  }),
  spec("SENTRY_DSN", {
    owners: ["@teak/convex", "@teak/web", "@teak/files-worker"],
    targets: ["convex", "web", "files-worker"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "url",
    providers: ["convex-dashboard", "vercel", "wrangler-secret"],
    required: false,
    note: "Convex and web fallback when the surface-specific DSN is unset; the worker's only DSN.",
  }),
  spec("SENTRY_AUTH_TOKEN", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets"],
    required: true,
    requiredIn: ["production"],
    note: "Release-only sourcemap upload credential. Never a local default.",
  }),
  spec("SENTRY_ORG", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: false,
    implicit: true,
    note: "Consumed by sentry-cli during releases.",
  }),
  spec("SENTRY_PROJECT", {
    owners: ["teak-release"],
    targets: ["release"],
    profiles: ["production"],
    secret: false,
    validation: "string",
    providers: ["workflow"],
    required: false,
    implicit: true,
    note: "Consumed by sentry-cli during releases.",
  }),
  // Administration.
  spec("TEAK_ADMIN_EMAIL", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["local", "preview", "production"],
    secret: false,
    validation: "email",
    providers: ["convex-dashboard"],
    required: false,
  }),
  // E2E backend capability group.
  spec("E2E_CLEANUP_TOKEN", {
    owners: ["@teak/convex", "@teak/tests"],
    targets: ["convex", "e2e"],
    profiles: ["e2e"],
    secret: true,
    validation: "string",
    providers: ["convex-dashboard", "github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
  }),
  spec("E2E_EMAIL_DOMAIN", {
    owners: ["@teak/convex", "@teak/tests"],
    targets: ["convex", "e2e"],
    profiles: ["e2e"],
    secret: false,
    validation: "string",
    providers: ["convex-dashboard", "github-secrets", "dotenv-local"],
    required: true,
    requiredIn: ["e2e"],
  }),
  // Convex deployment plumbing.
  spec("CONVEX_DEPLOY_KEY", {
    owners: ["@teak/convex"],
    targets: ["convex", "release"],
    profiles: ["preview", "production"],
    secret: true,
    validation: "string",
    providers: ["github-secrets", "dotenv-local"],
    required: false,
    note: "Selects a deployment for non-interactive Convex CLI runs. Setup refuses it locally.",
  }),
  spec("CONVEX_GIT_COMMIT_SHA", {
    owners: ["@teak/convex"],
    targets: ["convex"],
    profiles: ["preview", "production"],
    secret: false,
    validation: "sha",
    providers: ["workflow"],
    required: false,
    note: "Stamped by Backend Deploy for the backend Sentry release.",
  }),
];
