/**
 * Derived local dotenv files for setup (issue #407, Phase 4).
 *
 * One template and one create-or-repair helper for every setup-generated
 * file (web, extension, mobile). Generated files are never
 * overwritten: existing custom values win, missing keys are appended.
 */

import { randomBytes } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname } from "node:path";

export const LOCAL_CONVEX_URL = "http://127.0.0.1:3210";
export const LOCAL_CONVEX_SITE_URL = "http://127.0.0.1:3211";

/** One template for every setup-generated dotenv file. */
export const derivedEnvTemplate = (entries: Record<string, string>): string =>
  [
    "# Generated by bun run setup. Local only; never commit.",
    ...Object.entries(entries).map(([name, value]) => `${name}=${value}`),
    "",
  ].join("\n");

export const webEnvTemplate = (overrides?: {
  convexUrl?: string;
  convexSiteUrl?: string;
  siteUrl?: string;
}): string =>
  derivedEnvTemplate({
    NEXT_PUBLIC_CONVEX_URL: overrides?.convexUrl ?? LOCAL_CONVEX_URL,
    NEXT_PUBLIC_CONVEX_SITE_URL:
      overrides?.convexSiteUrl ?? LOCAL_CONVEX_SITE_URL,
    NEXT_PUBLIC_WORKOS_REDIRECT_URI: new URL(
      "/callback",
      overrides?.siteUrl ?? "http://localhost:3000"
    ).toString(),
  });

export const extensionEnvTemplate = (values: {
  convexUrl: string;
  convexSiteUrl: string;
}): string =>
  derivedEnvTemplate({
    VITE_PUBLIC_CONVEX_URL: values.convexUrl,
    VITE_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
  });

export const mobileEnvTemplate = (values: {
  convexUrl: string;
  convexSiteUrl: string;
}): string =>
  derivedEnvTemplate({
    EXPO_PUBLIC_CONVEX_URL: values.convexUrl,
    EXPO_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
  });

export const ensureFile = (
  path: string,
  contents: string
): "created" | "exists" => {
  if (existsSync(path)) {
    return "exists";
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, { mode: 0o600 });
  return "created";
};

/**
 * A generated value that points at this machine: a loopback URL, or the
 * emulator port next to WORKOS_API_HOSTNAME=localhost. Setup derives these
 * from the checkout's ports, so it refreshes them when the ports change.
 * Every other value is a person's and is never overwritten.
 */
export const isMachineLocalValue = (key: string, value: string): boolean => {
  if (key === "WORKOS_API_PORT") {
    return /^\d+$/.test(value);
  }
  try {
    const { hostname } = new URL(value);
    return ["localhost", "127.0.0.1", "[::1]"].includes(hostname);
  } catch {
    return false;
  }
};

export interface DerivedEnvOptions {
  /** Keys to drop: generated wiring that no longer applies. */
  remove?: readonly string[];
  /** Keys whose values another source owns; they always follow `entries`. */
  synced?: readonly string[];
}

/**
 * Create or repair a derived dotenv file. Missing keys are appended, synced
 * keys follow their source, and machine-local values (left by an earlier
 * local stack or other ports) are refreshed; custom values are never
 * overwritten.
 */
export const ensureDerivedEnv = (
  path: string,
  entries: Record<string, string>,
  options: DerivedEnvOptions = {}
): "created" | "exists" | "repaired" => {
  const created = ensureFile(path, derivedEnvTemplate(entries));
  if (created === "created") {
    return "created";
  }
  const lines = readFileSync(path, "utf-8").replace(/\s+$/, "").split("\n");
  const present = new Set<string>();
  let changed = false;
  const updated = lines.flatMap((line) => {
    if (!line.includes("=") || line.startsWith("#")) {
      return [line];
    }
    const key = line.split("=", 1)[0]?.trim() ?? "";
    if (options.remove?.includes(key)) {
      changed = true;
      return [];
    }
    present.add(key);
    const value = line.slice(line.indexOf("=") + 1).trim();
    const wanted = entries[key];
    if (
      wanted === undefined ||
      value === wanted ||
      !(options.synced?.includes(key) || isMachineLocalValue(key, value))
    ) {
      return [line];
    }
    changed = true;
    return [`${key}=${wanted}`];
  });
  const missing = Object.keys(entries).filter((key) => !present.has(key));
  if (missing.length === 0 && !changed) {
    return "exists";
  }
  const additions = missing.map((key) => `${key}=${entries[key]}`);
  writeFileSync(path, `${[...updated, ...additions].join("\n")}\n`, "utf-8");
  return "repaired";
};

/** The local WorkOS emulator's web wiring, which the dev web app never uses. */
const EMULATOR_WEB_KEYS = [
  "WORKOS_API_HOSTNAME",
  "WORKOS_API_PORT",
  "WORKOS_API_HTTPS",
] as const;

export const ensureWebEnv = (
  path: string,
  values: {
    convexUrl: string;
    convexSiteUrl: string;
    siteUrl: string;
    /** WorkOS client ID and API key, synced from the Convex deployment. */
    workos: Partial<Record<"WORKOS_CLIENT_ID" | "WORKOS_API_KEY", string>>;
  }
): "created" | "exists" | "repaired" => {
  // Tighten existing permissions before a repair can append secrets.
  if (existsSync(path)) {
    chmodSync(path, 0o600);
  }
  const result = ensureDerivedEnv(
    path,
    {
      ...values.workos,
      NEXT_PUBLIC_CONVEX_URL: values.convexUrl,
      NEXT_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
      NEXT_PUBLIC_WORKOS_REDIRECT_URI: new URL(
        "/callback",
        values.siteUrl
      ).toString(),
      WORKOS_COOKIE_PASSWORD: randomBytes(32).toString("base64url"),
    },
    {
      synced: Object.keys(values.workos),
      remove: EMULATOR_WEB_KEYS,
    }
  );
  // This file holds the WorkOS API key and the AuthKit session seal.
  chmodSync(path, 0o600);
  return result;
};
