/**
 * Derived local dotenv files for setup (issue #407, Phase 4).
 *
 * One template and one create-or-repair helper for every setup-generated
 * file (web, desktop, extension, mobile). Generated files are never
 * overwritten: existing custom values win, missing keys are appended.
 */

import { randomBytes } from "node:crypto";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname } from "node:path";

export const LOCAL_CONVEX_URL = "http://127.0.0.1:3210";
export const LOCAL_CONVEX_SITE_URL = "http://127.0.0.1:3211";

/** One template for every setup-generated dotenv file. */
export const derivedEnvTemplate = (entries: Record<string, string>): string =>
  [
    "# Generated by bun run setup. Local only; never commit.",
    ...Object.entries(entries).map(([name, value]) => `${name}=${value}`),
    "",
  ].join("\n");

export const webEnvTemplate = (overrides?: {
  convexUrl?: string;
  convexSiteUrl?: string;
  siteUrl?: string;
}): string =>
  derivedEnvTemplate({
    NEXT_PUBLIC_CONVEX_URL: overrides?.convexUrl ?? LOCAL_CONVEX_URL,
    NEXT_PUBLIC_CONVEX_SITE_URL:
      overrides?.convexSiteUrl ?? LOCAL_CONVEX_SITE_URL,
    NEXT_PUBLIC_WORKOS_REDIRECT_URI: new URL(
      "/callback",
      overrides?.siteUrl ?? "http://localhost:3000"
    ).toString(),
  });

export const desktopEnvTemplate = (values: {
  convexUrl: string;
  convexSiteUrl: string;
  webUrl: string;
}): string =>
  derivedEnvTemplate({
    VITE_PUBLIC_CONVEX_URL: values.convexUrl,
    VITE_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
    VITE_WEB_URL: values.webUrl,
  });

export const extensionEnvTemplate = (values: {
  convexUrl: string;
  convexSiteUrl: string;
}): string =>
  derivedEnvTemplate({
    VITE_PUBLIC_CONVEX_URL: values.convexUrl,
    VITE_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
  });

export const mobileEnvTemplate = (values: {
  convexUrl: string;
  convexSiteUrl: string;
}): string =>
  derivedEnvTemplate({
    EXPO_PUBLIC_CONVEX_URL: values.convexUrl,
    EXPO_PUBLIC_CONVEX_SITE_URL: values.convexSiteUrl,
  });

export const ensureFile = (
  path: string,
  contents: string
): "created" | "exists" => {
  if (existsSync(path)) {
    return "exists";
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents, { mode: 0o600 });
  return "created";
};

/** Create or repair a derived dotenv file; never overwrite custom values. */
export const ensureDerivedEnv = (
  path: string,
  entries: Record<string, string>
): "created" | "exists" | "repaired" => {
  const created = ensureFile(path, derivedEnvTemplate(entries));
  if (created === "created") {
    return "created";
  }
  const content = readFileSync(path, "utf-8");
  const present = new Set(
    content
      .split("\n")
      .filter((line) => line.includes("=") && !line.startsWith("#"))
      .map((line) => line.split("=", 1)[0]?.trim())
  );
  const missing = Object.keys(entries).filter((key) => !present.has(key));
  if (missing.length === 0) {
    return "exists";
  }
  const additions = missing.map((key) => `${key}=${entries[key]}`).join("\n");
  writeFileSync(
    path,
    `${content.replace(/\s+$/, "")}\n${additions}\n`,
    "utf-8"
  );
  return "repaired";
};

export const ensureWebEnv = (
  path: string,
  defaults?: {
    convexUrl?: string;
    convexSiteUrl?: string;
    siteUrl?: string;
    /** WorkOS client ID and API key, synced from the Convex deployment. */
    workos?: Partial<Record<"WORKOS_CLIENT_ID" | "WORKOS_API_KEY", string>>;
  }
): "created" | "exists" | "repaired" => {
  // Tighten existing permissions before a repair can append secrets.
  if (existsSync(path)) {
    chmodSync(path, 0o600);
  }
  const result = ensureDerivedEnv(path, {
    ...defaults?.workos,
    NEXT_PUBLIC_CONVEX_URL: defaults?.convexUrl ?? LOCAL_CONVEX_URL,
    NEXT_PUBLIC_CONVEX_SITE_URL:
      defaults?.convexSiteUrl ?? LOCAL_CONVEX_SITE_URL,
    NEXT_PUBLIC_WORKOS_REDIRECT_URI: new URL(
      "/callback",
      defaults?.siteUrl ?? "http://localhost:3000"
    ).toString(),
    WORKOS_COOKIE_PASSWORD: randomBytes(32).toString("base64url"),
  });
  // This file holds the WorkOS API key and the AuthKit session seal.
  chmodSync(path, 0o600);
  return result;
};
