#!/usr/bin/env bun
/**
 * Idempotent local bootstrap for agents and developers.
 *
 * 1. Check the Bun version pinned by `packageManager`.
 * 2. Run `bun ci` when node_modules is stale.
 * 3. Refuse an implicitly selected production Convex deployment.
 * 4. Preserve an existing isolated development deployment or provision one.
 * 5. Configure local SITE_URL (never overwrites a set value).
 * 6. Run `bunx convex dev --once` for push and code generation.
 * 7. Derive the ignored local web Convex configuration without overwriting
 *    custom values.
 *
 * Requires no production, OAuth, Apple, Cloudflare, billing, or release
 * credentials. Every step is check-then-act, so re-running setup changes
 * nothing once the tree is ready.
 *
 * Usage: bun run setup [--check]
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { parseConvexEnvOutput } from "./check-cloudflare.ts";

const ROOT = join(import.meta.dir, "..");
const CONVEX_PATH = join(ROOT, "packages/convex");
const CONVEX_ENV_PATH = join(CONVEX_PATH, ".env.local");
const WEB_ENV_PATH = join(ROOT, "apps/web/.env.local");

export const LOCAL_SITE_URL = "http://localhost:3000";
const LOCAL_CONVEX_URL = "http://127.0.0.1:3210";
const LOCAL_CONVEX_SITE_URL = "http://127.0.0.1:3211";

const runCommand = async (
  command: string[],
  opts?: { cwd?: string; timeoutMs?: number }
): Promise<{ exitCode: number; stdout: string; stderr: string }> => {
  const proc = Bun.spawn(command, {
    cwd: opts?.cwd ?? ROOT,
    stderr: "pipe",
    stdin: "ignore",
    stdout: "pipe",
  });
  const timeoutMs = opts?.timeoutMs ?? 180_000;
  const timer = setTimeout(() => {
    try {
      proc.kill();
    } catch {}
  }, timeoutMs);
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  clearTimeout(timer);
  return { exitCode: exitCode ?? 1, stdout, stderr };
};

export const requiredBunVersion = (packageManager: string): string => {
  const match = /^bun@(\d+\.\d+\.\d+)$/.exec(packageManager.trim());
  if (!match) {
    throw new Error(
      `Unsupported packageManager "${packageManager}" (expected bun@x.y.z)`
    );
  }
  return match[1];
};

export const checkBunVersion = (
  actual: string,
  required: string
): "ok" | "warn" | "mismatch" => {
  if (actual === required) {
    return "ok";
  }
  const [actualMajor, actualMinor] = actual.split(".");
  const [requiredMajor, requiredMinor] = required.split(".");
  return actualMajor === requiredMajor && actualMinor === requiredMinor
    ? "warn"
    : "mismatch";
};

export const webEnvTemplate = (overrides?: {
  convexUrl?: string;
  convexSiteUrl?: string;
}): string =>
  `${[
    "# Generated by bun run setup. Local only; never commit.",
    `NEXT_PUBLIC_CONVEX_URL=${overrides?.convexUrl ?? LOCAL_CONVEX_URL}`,
    `NEXT_PUBLIC_CONVEX_SITE_URL=${overrides?.convexSiteUrl ?? LOCAL_CONVEX_SITE_URL}`,
  ].join("\n")}\n`;

export const ensureFile = (
  path: string,
  contents: string
): "created" | "exists" => {
  if (existsSync(path)) {
    return "exists";
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  return "created";
};

export const ensureWebEnv = (
  path: string,
  defaults?: { convexUrl?: string; convexSiteUrl?: string }
): "created" | "exists" | "repaired" => {
  const template = webEnvTemplate(defaults);
  const created = ensureFile(path, template);
  if (created === "created") {
    return "created";
  }
  const expected = new Map(
    template
      .split("\n")
      .filter((line) => line.includes("=") && !line.startsWith("#"))
      .map((line) => line.split("=", 2) as [string, string])
  );
  const content = readFileSync(path, "utf-8");
  const present = new Set(
    content
      .split("\n")
      .filter((line) => line.includes("=") && !line.startsWith("#"))
      .map((line) => line.split("=", 1)[0]?.trim())
  );
  const missing = [...expected.keys()].filter((key) => !present.has(key));
  if (missing.length === 0) {
    return "exists";
  }
  const additions = missing
    .map((key) => `${key}=${expected.get(key)}`)
    .join("\n");
  writeFileSync(
    path,
    `${content.replace(/\s+$/, "")}\n${additions}\n`,
    "utf-8"
  );
  return "repaired";
};

export const isInstallStale = (root: string): boolean => {
  const modules = join(root, "node_modules");
  const lock = join(root, "bun.lock");
  if (!(existsSync(modules) && existsSync(lock))) {
    return true;
  }
  return statSync(lock).mtimeMs > statSync(modules).mtimeMs;
};

export const parseDotenvValue = (
  content: string,
  name: string
): string | undefined => {
  for (const line of content.replace(/\r\n/g, "\n").split("\n")) {
    const trimmed = line.trim();
    if (!(trimmed && !trimmed.startsWith("#") && trimmed.includes("="))) {
      continue;
    }
    const key = trimmed.slice(0, trimmed.indexOf("=")).trim();
    if (key !== name) {
      continue;
    }
    return trimmed
      .slice(trimmed.indexOf("=") + 1)
      .trim()
      .replace(/^(['"])(.*)\1$/, "$2");
  }
};

export type ConvexSelectionSource = "env" | "dotenv" | "none";

export interface ConvexSelection {
  deployment?: string;
  source: ConvexSelectionSource;
}

export const readConvexSelection = (
  env: NodeJS.ProcessEnv = process.env,
  dotenvPath: string = CONVEX_ENV_PATH
): ConvexSelection => {
  const fromEnv = env.CONVEX_DEPLOYMENT?.trim();
  if (fromEnv) {
    return { deployment: fromEnv, source: "env" };
  }
  if (existsSync(dotenvPath)) {
    const fromDotenv = parseDotenvValue(
      readFileSync(dotenvPath, "utf-8"),
      "CONVEX_DEPLOYMENT"
    )?.trim();
    if (fromDotenv) {
      return { deployment: fromDotenv, source: "dotenv" };
    }
  }
  return { source: "none" };
};

export const isProductionDeployment = (deployment?: string): boolean =>
  deployment?.startsWith("prod:") ?? false;

export const assertNoProductionConvex = (
  selection: ConvexSelection,
  deployKey?: string
): void => {
  if (deployKey?.trim()) {
    throw new Error(
      "Refusing setup with CONVEX_DEPLOY_KEY set: the key implicitly selects " +
        "the production deployment. Unset CONVEX_DEPLOY_KEY (setup never uses " +
        "production credentials) and re-run bun run setup."
    );
  }
  if (isProductionDeployment(selection.deployment)) {
    throw new Error(
      `Refusing setup against the production Convex deployment (${selection.deployment}). ` +
        "Point CONVEX_DEPLOYMENT at an isolated development deployment or " +
        "unset it so setup can provision one."
    );
  }
};

export const readConvexDotenvUrls = (
  dotenvPath: string = CONVEX_ENV_PATH
): { convexUrl?: string; convexSiteUrl?: string } => {
  if (!existsSync(dotenvPath)) {
    return {};
  }
  const content = readFileSync(dotenvPath, "utf-8");
  const convexUrl = parseDotenvValue(content, "NEXT_PUBLIC_CONVEX_URL");
  const convexSiteUrl = parseDotenvValue(
    content,
    "NEXT_PUBLIC_CONVEX_SITE_URL"
  );
  return {
    ...(convexUrl ? { convexUrl } : {}),
    ...(convexSiteUrl ? { convexSiteUrl } : {}),
  };
};

const convexEnvGet = async (
  name: string
): Promise<
  | { status: "found" }
  | { status: "missing" }
  | { status: "unavailable"; detail: string }
> => {
  try {
    const result = await runCommand(["bunx", "convex", "env", "get", name], {
      cwd: CONVEX_PATH,
      timeoutMs: 60_000,
    });
    const parsed = parseConvexEnvOutput(
      result.stdout,
      result.stderr,
      result.exitCode
    );
    if (parsed.status === "found") {
      return { status: "found" };
    }
    if (parsed.status === "missing") {
      return { status: "missing" };
    }
    const detail = result.stderr.trim().split("\n").pop() || "unknown error";
    return { status: "unavailable", detail };
  } catch (error) {
    return {
      status: "unavailable",
      detail: error instanceof Error ? error.message : "spawn failed",
    };
  }
};

const convexEnvSet = async (
  name: string,
  value: string
): Promise<{ ok: boolean; detail: string }> => {
  const result = await runCommand(
    ["bunx", "convex", "env", "set", name, value],
    { cwd: CONVEX_PATH, timeoutMs: 60_000 }
  );
  return {
    detail:
      result.exitCode === 0
        ? "configured"
        : result.stderr.trim().split("\n").pop() || "unknown error",
    ok: result.exitCode === 0,
  };
};

const convexDevOnce = async (): Promise<{ ok: boolean; detail: string }> => {
  const result = await runCommand(["bunx", "convex", "dev", "--once"], {
    cwd: CONVEX_PATH,
    timeoutMs: 300_000,
  });
  return {
    detail:
      result.exitCode === 0
        ? "pushed"
        : result.stderr.trim().split("\n").slice(-3).join(" ") ||
          "unknown error",
    ok: result.exitCode === 0,
  };
};

const main = async (): Promise<void> => {
  const checkOnly = process.argv.includes("--check");

  const packageJson = JSON.parse(
    readFileSync(join(ROOT, "package.json"), "utf-8")
  ) as { packageManager?: string };
  if (!packageJson.packageManager) {
    throw new Error("packageManager is not pinned in package.json");
  }
  const required = requiredBunVersion(packageJson.packageManager);
  const bunStatus = checkBunVersion(Bun.version, required);
  if (bunStatus === "mismatch") {
    throw new Error(
      `Bun ${required} is required (found ${Bun.version}). Install the pinned version and re-run.`
    );
  }
  console.log(
    `Bun ${Bun.version} ${bunStatus === "ok" ? "matches" : `~ ${required} (patch drift ok)`} pinned ${required}`
  );

  if (isInstallStale(ROOT)) {
    if (checkOnly) {
      console.log("Dependencies: stale (would run bun ci)");
    } else {
      console.log("Dependencies: stale (running bun ci)");
      const install = await runCommand(["bun", "ci"], { timeoutMs: 300_000 });
      if (install.exitCode !== 0) {
        throw new Error(
          `bun ci failed: ${install.stderr.trim().split("\n").pop() || "unknown error"}`
        );
      }
    }
  } else {
    console.log("Dependencies: fresh");
  }

  const selection = readConvexSelection();
  assertNoProductionConvex(selection, process.env.CONVEX_DEPLOY_KEY);
  if (selection.deployment) {
    console.log(
      `Convex deployment: preserving ${selection.deployment} (from ${selection.source})`
    );
  } else {
    console.log(
      "Convex deployment: none selected (convex dev will provision an isolated development deployment)"
    );
  }

  // Provision first when nothing is selected: the first push may fail on
  // the missing SITE_URL, which the next step configures before the final
  // push. Best-effort here; the final push below must succeed.
  if (!(selection.deployment || checkOnly)) {
    const provision = await convexDevOnce();
    console.log(
      `Convex provision: ${provision.ok ? provision.detail : `deferred (${provision.detail})`}`
    );
  }

  if (checkOnly) {
    console.log(
      "SITE_URL: would verify with `convex env get SITE_URL` and set the local default when missing"
    );
    console.log(
      "Convex push: would run `bunx convex dev --once` in packages/convex"
    );
  } else {
    const siteUrl = await convexEnvGet("SITE_URL");
    if (siteUrl.status === "found") {
      console.log("SITE_URL: already set on the selected deployment");
    } else if (siteUrl.status === "missing") {
      const set = await convexEnvSet("SITE_URL", LOCAL_SITE_URL);
      if (!set.ok) {
        throw new Error(`Could not set SITE_URL: ${set.detail}`);
      }
      console.log(`SITE_URL: configured local default ${LOCAL_SITE_URL}`);
    } else {
      throw new Error(
        `Could not read SITE_URL from the selected deployment: ${siteUrl.detail}. ` +
          "Run `bunx convex login` (or export CONVEX_AGENT_MODE=anonymous for a local anonymous deployment) and re-run bun run setup."
      );
    }

    const push = await convexDevOnce();
    if (!push.ok) {
      throw new Error(`convex dev --once failed: ${push.detail}`);
    }
    console.log("Convex push: code pushed and types generated");
  }

  if (checkOnly) {
    console.log(
      "Web env: would derive apps/web/.env.local from the active Convex deployment without overwriting custom values"
    );
  } else {
    const derived = readConvexDotenvUrls();
    console.log(`Web env: ${ensureWebEnv(WEB_ENV_PATH, derived)}`);
  }

  console.log(
    checkOnly ? "setup --check: ok" : "setup: complete (re-run is a no-op)"
  );
};

if (import.meta.main) {
  try {
    await main();
  } catch (error) {
    console.error(
      `setup failed: ${error instanceof Error ? error.message : String(error)}`
    );
    process.exitCode = 1;
  }
}
