package com.praveenjuge.teak.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Generated with Material Color Utilities from Teak red (#DC2626): the fidelity scheme keeps the
// brand red for primary actions; secondary roles (chips, tab indicators, tonal buttons) and surfaces
// are warm neutrals, so red stays an accent and saved images stay the center of attention.

internal val lightScheme = lightColorScheme(
    primary = Color(0xFFB70011),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDC2626),
    onPrimaryContainer = Color(0xFFFFF6F5),
    secondary = Color(0xFF665D5C),
    onSecondary = Color(0xFFFFF7F6),
    secondaryContainer = Color(0xFFEDE0DE),
    onSecondaryContainer = Color(0xFF58504F),
    tertiary = Color(0xFF005E8D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF0078B2),
    onTertiaryContainer = Color(0xFFF3F8FF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    inversePrimary = Color(0xFFFFB4AB),
    surfaceTint = Color(0xFFBF0715),
    background = Color(0xFFFFF8F7),
    onBackground = Color(0xFF373130),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF373130),
    surfaceVariant = Color(0xFFEBE0DF),
    onSurfaceVariant = Color(0xFF655D5C),
    outline = Color(0xFF817978),
    outlineVariant = Color(0xFFB9B0AE),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF100E0D),
    inverseOnSurface = Color(0xFFA19C9B),
    surfaceDim = Color(0xFFE3D7D6),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFAF2F1),
    surfaceContainer = Color(0xFFF5ECEB),
    surfaceContainerHigh = Color(0xFFF0E6E5),
    surfaceContainerHighest = Color(0xFFEBE0DF),
)

internal val darkScheme = darkColorScheme(
    primary = Color(0xFFFFB4AB),
    onPrimary = Color(0xFF690005),
    primaryContainer = Color(0xFFDC2626),
    onPrimaryContainer = Color(0xFFFFF6F5),
    secondary = Color(0xFFA69B9A),
    onSecondary = Color(0xFF251F1E),
    secondaryContainer = Color(0xFF413A39),
    onSecondaryContainer = Color(0xFFC9BDBB),
    tertiary = Color(0xFF90CDFF),
    onTertiary = Color(0xFF003450),
    tertiaryContainer = Color(0xFF0078B2),
    onTertiaryContainer = Color(0xFFF3F8FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    inversePrimary = Color(0xFFBF0715),
    surfaceTint = Color(0xFFFFB4AB),
    background = Color(0xFF100E0D),
    onBackground = Color(0xFFEEE3E2),
    surface = Color(0xFF100E0D),
    onSurface = Color(0xFFEEE3E2),
    surfaceVariant = Color(0xFF2A2524),
    onSurfaceVariant = Color(0xFFB2A9A8),
    outline = Color(0xFF7C7473),
    outlineVariant = Color(0xFF4D4646),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFFFF8F7),
    inverseOnSurface = Color(0xFF585454),
    surfaceDim = Color(0xFF100E0D),
    surfaceBright = Color(0xFF312B2A),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceContainerLow = Color(0xFF161312),
    surfaceContainer = Color(0xFF1C1918),
    surfaceContainerHigh = Color(0xFF231F1E),
    surfaceContainerHighest = Color(0xFF2A2524),
)
