#!/usr/bin/env sh

# Run lint-staged for file-specific checks
bunx lint-staged

# Check that TypeScript compiles without errors
echo "Checking TypeScript compilation..."
bunx tsc --noEmit

# Check that web app builds successfully  
echo "Checking web app builds..."
cd apps/web && bun run build

# Check that docs builds successfully
echo "Checking web app builds..."
cd ../.. && cd apps/docs && bun run build

# Check that extension builds successfully
echo "Checking web app builds..."
cd ../.. && cd apps/extension && bun run build
